name: Deploy to Production

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version to deploy (e.g. 5)'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Останавливаем старый контейнер
            docker stop shri-app || true
            docker rm shri-app || true
            
            # Авторизация в Container Registry
            echo ${{ secrets.YC_OAUTH_TOKEN }} | docker login \
              --username oauth \
              --password-stdin \
              cr.yandex
            
            # Запускаем новый контейнер
            docker run -d \
              --name shri-app \
              -p 80:3000 \
              --restart unless-stopped \
              cr.yandex/${{ secrets.YC_REGISTRY_ID }}/app:${{ github.event.inputs.version }}_latest