name: Deploy to Production

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version to deploy (e.g. 5)'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: jeky_samyelson
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo docker stop shri-app || true
            sudo docker rm shri-app || true
            echo ${{ secrets.YC_OAUTH_TOKEN }} | sudo docker login --username oauth --password-stdin cr.yandex
            sudo docker run -d --name shri-app -p 80:3000 --restart unless-stopped cr.yandex/${{ secrets.YC_REGISTRY_ID }}/app:latest